version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-8080}:${BACKEND_PORT_INTERNAL:-8080}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/pagina
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=2713
      # Esta linha abaixo força o Hibernate a usar o dialeto correto mesmo sem ver os metadados antes
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    networks:
      - app-network
    # Garante que o banco suba antes do backend
    depends_on:
      - postgres_db 

networks:
  app-network:
    external: true