version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-backend
    restart: unless-stopped
    # O command agora vai funcionar porque mudamos para CMD no Dockerfile
    command: >
      java -Dspring.datasource.url=jdbc:postgresql://postgres_db:5432/${DB_NAME}
           -Dspring.datasource.username=${DB_USER}
           -Dspring.datasource.password=${DB_PASSWORD}
           -Dspring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
           -jar app.jar
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network
    depends_on:
      - postgres_db 

networks:
  app-network:
    external: true