spring.application.name=projeto
server.address=0.0.0.0
server.port=${PORT:8080}

# CONFIGURAÇÃO DO BANCO (O Railway já fornece as variáveis abaixo)
# O prefixo jdbc: deve ir APENAS na URL
spring.datasource.url=jdbc:postgresql://postgres_db:5432/pagina
spring.datasource.username=postgres
spring.datasource.password=2713
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MULTIPART
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# LOGS (Útil para debugar, mas pode desativar depois)
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# SEGURANÇA
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration