spring.profiles.active=${APP_PROFILE:local}
HETZNER_HOST=89.167.42.44
HETZNER_USER=root
HETZNER_PASS=Ferinha_@2713
HETZNER_REMOTE_PATH=/root/virtualNfc/fotos/
HETZNER_BASE_URL=https://images.virtualnfc.com/

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB