spring.datasource.url=jdbc:postgresql://localhost:5432/pagina
spring.datasource.username=postgres
spring.datasource.password=2713
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=inspection


spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.error.include-stacktrace=never
logging.level.root=INFO
spring.jpa.hibernate.ddl-auto=create

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=contatohappytimebrinquedos@gmail.com
spring.mail.password=RePPYt1m3
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


aws.access.key=DO00MVPPJNJ8MEQH4CN9
aws.secret.key=k/YrrPeiTtIlsVNX7JslzM51j1oRD3JHAnDTJuLWIMc
aws.s3.region=sfo3
aws.s3.bucket=virtualnfcbucket
# O endpoint deve ser o host sem o nome do bucket no início
aws.s3.endpoint=https://sfo3.digitaloceanspaces.com